'use client';

import React, { useState, useEffect } from 'react';
import { Card, CardBody, CardHeader } from '@heroui/card';
import { Button } from '@heroui/button';
import { Progress } from '@heroui/progress';
import { PhotoUpload } from '../photo-upload';

interface DocumentGenerationStepProps {
    onPhotoUpload: (file: File, type: 'user' | 'other') => void;
    onGenerateDocument: () => void;
    userPhoto?: File | null;
    otherPartyPhoto?: File | null;
    isUploading?: boolean;
    isGenerating?: boolean;
    className?: string;
}

export const DocumentGenerationStep: React.FC<DocumentGenerationStepProps> = ({
    onPhotoUpload,
    onGenerateDocument,
    userPhoto,
    otherPartyPhoto,
    isUploading = false,
    isGenerating = false,
    className = ""
}) => {
    const [uploadProgress, setUploadProgress] = useState(0);
    const [hasAutoGenerated, setHasAutoGenerated] = useState(false);

    const canGenerate = userPhoto && otherPartyPhoto && !isUploading;

    // Auto-generate document when both photos are uploaded
    useEffect(() => {
        if (canGenerate && !hasAutoGenerated && !isGenerating) {
            setHasAutoGenerated(true);
            // Small delay to show the "Ready" state briefly
            setTimeout(() => {
                onGenerateDocument();
            }, 1500);
        }
    }, [canGenerate, hasAutoGenerated, isGenerating, onGenerateDocument]);

    return (
        <div className={`w-full max-w-3xl space-y-8 ${className}`}>
            <Card>
                <CardHeader className="text-center pb-4">
                    <div className="space-y-4">
                        <div className="text-4xl">📄</div>
                        <h2 className="text-3xl font-bold text-gray-900">Generate Your Legal Case</h2>
                        <p className="text-lg text-gray-600 max-w-2xl mx-auto">
                            Upload photos of yourself and the other party to create a comprehensive legal case document.
                        </p>
                    </div>
                </CardHeader>

                <CardBody className="space-y-8">
                    {/* Instructions */}
                    <div className="bg-blue-50 border border-blue-200 rounded-lg p-6">
                        <h3 className="font-semibold text-blue-900 mb-3">📋 Required for Document Generation:</h3>
                        <ul className="space-y-2 text-blue-800">
                            <li className="flex items-center space-x-2">
                                <span className="w-2 h-2 bg-blue-500 rounded-full"></span>
                                <span><strong>Your photo</strong> - Clear identification picture (required)</span>
                            </li>
                            <li className="flex items-center space-x-2">
                                <span className="w-2 h-2 bg-blue-500 rounded-full"></span>
                                <span><strong>Other party photo</strong> - Picture of the other person involved (required)</span>
                            </li>
                            <li className="flex items-center space-x-2">
                                <span className="w-2 h-2 bg-blue-500 rounded-full"></span>
                                <span>Document generation will start automatically once both photos are uploaded</span>
                            </li>
                        </ul>
                    </div>

                    {/* Photo Upload Section */}
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                        {/* User Photo */}
                        <div className="space-y-4">
                            <div className="flex items-center justify-between">
                                <div className="flex items-center space-x-2">
                                    <h3 className="text-xl font-semibold text-gray-800">Your Photo</h3>
                                    <span className="text-red-500 text-sm font-medium">*Required</span>
                                </div>
                                {userPhoto && (
                                    <div className="w-6 h-6 bg-green-500 rounded-full flex items-center justify-center">
                                        <span className="text-white text-xs">✓</span>
                                    </div>
                                )}
                            </div>
                            <PhotoUpload
                                onFileSelect={(file) => onPhotoUpload(file, 'user')}
                                selectedFile={userPhoto}
                                placeholder="Upload your photo"
                                className="h-64"
                            />
                            {userPhoto && (
                                <div className="text-sm text-gray-600 text-center">
                                    ✅ Photo uploaded: {userPhoto.name}
                                </div>
                            )}
                        </div>

                        {/* Other Party Photo */}
                        <div className="space-y-4">
                            <div className="flex items-center justify-between">
                                <div className="flex items-center space-x-2">
                                    <h3 className="text-xl font-semibold text-gray-800">Other Party Photo</h3>
                                    <span className="text-red-500 text-sm font-medium">*Required</span>
                                </div>
                                {otherPartyPhoto && (
                                    <div className="w-6 h-6 bg-green-500 rounded-full flex items-center justify-center">
                                        <span className="text-white text-xs">✓</span>
                                    </div>
                                )}
                            </div>
                            <PhotoUpload
                                onFileSelect={(file) => onPhotoUpload(file, 'other')}
                                selectedFile={otherPartyPhoto}
                                placeholder="Upload other party photo"
                                className="h-64"
                            />
                            {otherPartyPhoto && (
                                <div className="text-sm text-gray-600 text-center">
                                    ✅ Photo uploaded: {otherPartyPhoto.name}
                                </div>
                            )}
                        </div>
                    </div>

                    {/* Upload Progress */}
                    {isUploading && (
                        <div className="space-y-3">
                            <div className="flex items-center justify-between">
                                <span className="text-sm font-medium text-gray-700">Uploading photos...</span>
                                <span className="text-sm text-gray-500">{uploadProgress}%</span>
                            </div>
                            <Progress
                                value={uploadProgress}
                                className="w-full"
                                color="primary"
                                size="md"
                            />
                        </div>
                    )}

                    {/* Generate Button */}
                    <div className="text-center space-y-4">
                        {canGenerate ? (
                            <div className="space-y-4">
                                {isGenerating ? (
                                    <div className="bg-blue-50 border border-blue-200 rounded-lg p-6">
                                        <div className="text-blue-800 font-medium text-lg mb-2">
                                            🔄 Generating Your Legal Case Document...
                                        </div>
                                        <div className="text-blue-600 text-sm">
                                            Please wait while we create your comprehensive case document
                                        </div>
                                    </div>
                                ) : hasAutoGenerated ? (
                                    <div className="bg-green-50 border border-green-200 rounded-lg p-6">
                                        <div className="text-green-800 font-medium text-lg mb-2">
                                            ✅ Both Photos Uploaded Successfully!
                                        </div>
                                        <div className="text-green-600 text-sm">
                                            Starting document generation automatically...
                                        </div>
                                    </div>
                                ) : (
                                    <div className="bg-green-50 border border-green-200 rounded-lg p-6">
                                        <div className="text-green-800 font-medium text-lg mb-2">
                                            ✅ Ready to Generate Your Legal Case Document!
                                        </div>
                                        <div className="text-green-600 text-sm">
                                            Both photos uploaded - document generation will start automatically
                                        </div>
                                    </div>
                                )}
                            </div>
                        ) : (
                            <div className="space-y-4">
                                <div className="bg-amber-50 border border-amber-200 rounded-lg p-6">
                                    <div className="text-amber-800 font-medium text-lg mb-2">
                                        📸 Upload Required Photos
                                    </div>
                                    <div className="text-amber-700 text-sm">
                                        Please upload both your photo and the other party's photo to continue
                                    </div>
                                    <div className="mt-3 flex items-center justify-center space-x-6 text-sm">
                                        <div className={`flex items-center space-x-2 ${userPhoto ? 'text-green-600' : 'text-gray-500'}`}>
                                            <span>{userPhoto ? '✅' : '⏳'}</span>
                                            <span>Your Photo</span>
                                        </div>
                                        <div className={`flex items-center space-x-2 ${otherPartyPhoto ? 'text-green-600' : 'text-gray-500'}`}>
                                            <span>{otherPartyPhoto ? '✅' : '⏳'}</span>
                                            <span>Other Party Photo</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        )}
                    </div>

                    {/* Document Preview Info */}
                    <div className="bg-gray-50 border border-gray-200 rounded-lg p-6">
                        <h3 className="font-semibold text-gray-800 mb-3">📋 Your Document Will Include:</h3>
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-sm text-gray-700">
                            <div className="space-y-2">
                                <div className="flex items-center space-x-2">
                                    <span className="w-1.5 h-1.5 bg-gray-400 rounded-full"></span>
                                    <span>Complete incident timeline</span>
                                </div>
                                <div className="flex items-center space-x-2">
                                    <span className="w-1.5 h-1.5 bg-gray-400 rounded-full"></span>
                                    <span>Fault analysis and evidence</span>
                                </div>
                                <div className="flex items-center space-x-2">
                                    <span className="w-1.5 h-1.5 bg-gray-400 rounded-full"></span>
                                    <span>Legal recommendations</span>
                                </div>
                            </div>
                            <div className="space-y-2">
                                <div className="flex items-center space-x-2">
                                    <span className="w-1.5 h-1.5 bg-gray-400 rounded-full"></span>
                                    <span>Party identification photos</span>
                                </div>
                                <div className="flex items-center space-x-2">
                                    <span className="w-1.5 h-1.5 bg-gray-400 rounded-full"></span>
                                    <span>Case summary and details</span>
                                </div>
                                <div className="flex items-center space-x-2">
                                    <span className="w-1.5 h-1.5 bg-gray-400 rounded-full"></span>
                                    <span>Professional formatting</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </CardBody>
            </Card>
        </div>
    );
};
